version: '3'

services:
  # enovation:
  #   image: enovation:latest
  #   depends_on:
  #     - "db"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:80"
      
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enovation
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
